services:
  # リバースプロキシ用のApacheサーバー
  apache:
    image: httpd:2.4-alpine
    container_name: apache
    ports:
      - "18080:80" # ホストの80番ポートで外部からアクセスできるように設定
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf # Apacheの設定ファイルをコンテナにマウント
      - ./apache/images:/usr/local/apache2/htdocs/images/my-books # 書籍の画像ファイルをコンテナにマウント
      - ./apache/avatars:/usr/local/apache2/htdocs/images/avatars # アバター画像ファイルをコンテナにマウント
    depends_on:
      - spring-boot-app

  # Spring Bootアプリケーションのサービス
  spring-boot-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my-books-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  # MySQLデータベースのサービス
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-books-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    command: --secure-file-priv=/docker-entrypoint-initdb.d

volumes:
  db_data:
