services:
  # リバースプロキシ用のApacheサーバー
  apache:
    image: httpd:2.4-alpine
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf # Apacheの設定(httpd)
      - ./apache/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf # Apacheの設定(httpd-ssl)
      - ./apache/images:/usr/local/apache2/htdocs/images/my-books # 書籍の画像
      - ./apache/avatars:/usr/local/apache2/htdocs/images/avatars # アバター画像
      - ./apache/server.crt:/usr/local/apache2/conf/server.crt # 証明書
      - ./apache/server.key:/usr/local/apache2/conf/server.key # 秘密鍵
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - spring-boot-app

  # Spring Bootアプリケーションのサービス
  spring-boot-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my-books-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APP_JWT_SECRET: Ry9CqEZVzQH7k1234abcdefghijklmnopqrstuvwxyzABCD+/=
      SPRING_APP_JWT_ACCESS_EXPIRATION: 3600
      SPRING_APP_JWT_REFRESH_EXPIRATION: 86400
      TZ: Asia/Tokyo
    depends_on:
      - db

  # MySQLデータベースのサービス
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-books-db
      TZ: Asia/Tokyo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/books.csv:/docker-entrypoint-initdb.d/books.csv
      - ./db/book_genres.csv:/docker-entrypoint-initdb.d/book_genres.csv
      - ./db/book_content_pages.csv:/docker-entrypoint-initdb.d/book_content_pages.csv
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    command: --secure-file-priv=/docker-entrypoint-initdb.d

volumes:
  db_data:
