services:
  web:
    build:
      context: ./web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/certs:/etc/nginx/ssl
      - ./web/images:/usr/share/nginx/html/images
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - my-books-api

  my-books-api:
    build:
      context: ./api/my-books-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-books-db:3306/my-books-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APP_JWT_SECRET: Ry9CqEZVzQH7k1234abcdefghijklmnopqrstuvwxyzABCD+/=
      SPRING_APP_JWT_ACCESS_EXPIRATION: 3600
      SPRING_APP_JWT_REFRESH_EXPIRATION: 86400
      TZ: Asia/Tokyo
    expose:
      - "8080"
    depends_on:
      - my-books-db

  my-books-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-books-db
      TZ: Asia/Tokyo
    expose:
      - "3306"
    volumes:
      - ./db/my-books-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my-books-db/books.csv:/docker-entrypoint-initdb.d/books.csv
      - ./db/my-books-db/book_genres.csv:/docker-entrypoint-initdb.d/book_genres.csv
      - ./db/my-books-db/book_content_pages.csv:/docker-entrypoint-initdb.d/book_content_pages.csv
      - ./db/my-books-db/my.cnf:/etc/mysql/conf.d/my.cnf
      - my-books-db-data:/var/lib/mysql
    command: --secure-file-priv=/docker-entrypoint-initdb.d

volumes:
  my-books-db-data:
